  MK/Cursor-Revamp[m
  Manual_Hijri[m
  Mudasir-readjust[m
  Taraweeh_Ramadan[m
  add_sunrise[m
  auto_hijri[m
  clock_change[m
  clock_neg[m
  clock_top_change[m
  countdown[m
  countdown_add[m
  countdown_fix_date[m
  countdown_size[m
  date_fix[m
  daylightsavfix[m
  display_monthchange[m
  fix_countdown_date[m
  flashingcount[m
  hijri_auto[m
  hijri_man_function[m
  login_change[m
  manual_hijri_add[m
* [32mmaster[m
  mbranch[m
  new_branch[m
  taraweeh_reciters[m
  time_fix[m
  updates[m
  webscrapev1[m
  website_change[m
  webupdate[m
